name: Service

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1.0
    - name: BUILD SERVICE DOCKER IMAGE WITH V1.0
      run: docker build . --file Dockerfile --tag service:1.0
    - name: LOGIN TO DOCKER HUB
      run : docker login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: PUSH DOCKER IMAGE TO DOCKER HUB
      run : docker push service:1.0

