name: Service

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: BUILD SERVICE DOCKER IMAGE WITH V1.0
      run: docker build . --file Dockerfile --tag service:1.0
    - name: LOGIN TO DOCKER HUB
      run: docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: PUSH DOCKER IMAGE TO DOCKER HUB
      run : docker push ${{ secrets.DOCKER_HUB_USERNAME }}/service:1.0

